technical_agent:
  template: technical_fine.yaml
  price_series_lookback_days: 400
quant_fundamental_agent:
  template: quant_fundamental_fine.yaml
qualitative_fundamental_agent:
  template: qualitative_fine.yaml
news_agent:
  template: news_fine.yaml
sector_agent:
  template: sector_fine.yaml
macro_agent:
  template: macro_fine.yaml
pm_agent:
  template: pm_fine.yaml
