technical_agent: technical_fine.yaml
quant_fundamental_agent: quant_fundamental_fine.yaml
qualitative_fundamental_agent: qualitative_fine.yaml
news_agent: news_fine.yaml
sector_agent: sector_fine.yaml
macro_agent: macro_fine.yaml
pm_agent: pm_fine.yaml
