from datetime import date, datetime

from neocortex.agents import (
    MacroInput,
    MacroMetric,
    MetricRow,
    QualitativeFundamentalInput,
    QuantFundamentalInput,
    QuantMetric,
)
from tests.core._market_data_provider_fakes import InMemoryMarketDataProvider
from neocortex.models import (
    AgentResponse,
    AgentRole,
    CompanyProfile,
    Exchange,
    Market,
    NewsItem,
    PriceBar,
    PriceSeries,
    SecurityId,
)
from neocortex.pipeline import Pipeline


def _cn_security() -> SecurityId:
    return SecurityId(symbol="600519", market=Market.CN, exchange=Exchange.XSHG)


def _company_profile(security_id: SecurityId) -> CompanyProfile:
    return CompanyProfile(
        security_id=security_id,
        company_name="贵州茅台",
        sector="白酒",
        industry="白酒",
        country="CN",
        currency="CNY",
    )


def _price_series(security_id: SecurityId) -> PriceSeries:
    return PriceSeries(
        security_id=security_id,
        bars=(
            PriceBar(
                security_id=security_id,
                timestamp=datetime(2026, 3, 9, 15, 0),
                open=99.0,
                high=102.0,
                low=98.0,
                close=100.0,
                volume=1_000_000.0,
            ),
            PriceBar(
                security_id=security_id,
                timestamp=datetime(2026, 3, 10, 15, 0),
                open=101.0,
                high=104.0,
                low=100.0,
                close=102.0,
                volume=1_010_000.0,
            ),
            PriceBar(
                security_id=security_id,
                timestamp=datetime(2026, 3, 11, 15, 0),
                open=100.0,
                high=103.0,
                low=99.0,
                close=101.0,
                volume=1_020_000.0,
            ),
            PriceBar(
                security_id=security_id,
                timestamp=datetime(2026, 3, 12, 15, 0),
                open=104.0,
                high=107.0,
                low=103.0,
                close=105.0,
                volume=1_030_000.0,
            ),
            PriceBar(
                security_id=security_id,
                timestamp=datetime(2026, 3, 13, 15, 0),
                open=109.0,
                high=112.0,
                low=108.0,
                close=110.0,
                volume=1_040_000.0,
            ),
        ),
    )


def _pipeline() -> Pipeline:
    return Pipeline(
        market_data=InMemoryMarketDataProvider(
            company_profiles={_cn_security(): _company_profile(_cn_security())},
            price_bars={_cn_security(): _price_series(_cn_security())},
        ),
    )


def test_agent_prompt_baselines() -> None:
    security_id = _cn_security()
    company_profile = _company_profile(security_id)
    pipeline = _pipeline()

    technical_agent = pipeline.get_agent(AgentRole.TECHNICAL)
    quant_agent = pipeline.get_agent(AgentRole.QUANT_FUNDAMENTAL)
    qualitative_agent = pipeline.get_agent(AgentRole.QUALITATIVE_FUNDAMENTAL)
    news_agent = pipeline.get_agent(AgentRole.NEWS)
    sector_agent = pipeline.get_agent(AgentRole.SECTOR)
    macro_agent = pipeline.get_agent(AgentRole.MACRO)
    pm_agent = pipeline.get_agent(AgentRole.PM)

    technical_request = technical_agent.build_request(
        request_id="req-tech-rt-001",
        security_id=security_id,
        as_of_date=date(2026, 3, 13),
    )
    quant_request = quant_agent.build_request(
        request_id="req-quant-rt-001",
        security_id=security_id,
        as_of_date=date(2026, 3, 13),
        company_profile=company_profile,
        fundamentals=QuantFundamentalInput(
            current_date="2026-03-13",
            net_margin=QuantMetric(value="21%", diff="+1%"),
            roa=QuantMetric(value="12%", diff="+1%"),
            roe=QuantMetric(value="18%", diff="+2%"),
            asset_turn=QuantMetric(value="0.8", diff="+0.1"),
            inv_turn_days=QuantMetric(value="35", diff="-2"),
            per=QuantMetric(value="28", diff="+1"),
            fcf=QuantMetric(value="45", diff="+3%"),
            fcf_margin=QuantMetric(value="15%", diff="+1%"),
            ebitda=QuantMetric(value="60", diff="+4%"),
            equity_ratio=QuantMetric(value="55%", diff="+1%"),
            quick_ratio=QuantMetric(value="1.4", diff="+0.1"),
            de_ratio=QuantMetric(value="0.3", diff="-0.1"),
            sales_yoy=QuantMetric(value="10%", diff="+2%"),
            cagr_3y=QuantMetric(value="8%", diff="+1%"),
            eps_growth=QuantMetric(value="12%", diff="+3%"),
            dps=QuantMetric(value="4.2", diff="+0.2"),
        ),
    )
    qualitative_request = qualitative_agent.build_request(
        request_id="req-qual-rt-001",
        security_id=security_id,
        as_of_date=date(2026, 3, 13),
        company_profile=company_profile,
        disclosures=QualitativeFundamentalInput(
            info_update="Yes",
            overview="New channels are expanding.",
            risks="Input costs remain elevated.",
            mda="Margin recovery is underway.",
            governance="Board refresh is progressing.",
        ),
    )
    news_request = news_agent.build_request(
        request_id="req-news-rt-001",
        security_id=security_id,
        as_of_date=date(2026, 3, 13),
        company_profile=company_profile,
        news_items=(
            NewsItem(
                security_id=security_id,
                published_at=datetime(2026, 3, 12, 9, 0),
                source="ExampleWire",
                title="Premium line launched",
                summary="The company launched a premium line.",
                url="https://example.com/news/1",
            ),
        ),
    )
    sector_request = sector_agent.build_request(
        request_id="req-sector-rt-001",
        security_id=security_id,
        as_of_date=date(2026, 3, 13),
        company_profile=company_profile,
        comparison_rows=(
            MetricRow(
                section="Growth",
                label="Sales YoY",
                value="+12%",
                peer_value="+8%",
                change="+2%",
            ),
        ),
        analyst_reports=(
            AgentResponse(
                request_id="1",
                agent=AgentRole.TECHNICAL,
                security_id=security_id,
                as_of_date=date(2026, 3, 13),
                reasoning="Momentum is constructive.",
                score=72.0,
            ),
            AgentResponse(
                request_id="2",
                agent=AgentRole.QUANT_FUNDAMENTAL,
                security_id=security_id,
                as_of_date=date(2026, 3, 13),
                reasoning="Cash flow remains resilient.",
                score=68.0,
            ),
            AgentResponse(
                request_id="3",
                agent=AgentRole.QUALITATIVE_FUNDAMENTAL,
                security_id=security_id,
                as_of_date=date(2026, 3, 13),
                reasoning="Execution is improving.",
                score=None,
            ),
            AgentResponse(
                request_id="4",
                agent=AgentRole.NEWS,
                security_id=security_id,
                as_of_date=date(2026, 3, 13),
                reasoning="Newsflow remains constructive.",
                score=None,
            ),
        ),
    )
    macro_request = macro_agent.build_request(
        request_id="req-macro-rt-001",
        security_id=SecurityId(symbol="AAPL", market=Market.US, exchange=Exchange.XNAS),
        as_of_date=date(2026, 3, 13),
        macro_data=MacroInput(
            us_fed_rate=MacroMetric(value="5.25%", roc="0.0%"),
            us_10y_yield=MacroMetric(value="4.2%", roc="+0.1%"),
            jp_policy_rate=MacroMetric(value="0.5%", roc="0.0%"),
            jp_10y_yield=MacroMetric(value="1.1%", roc="+0.1%"),
            cn_policy_rate=MacroMetric(value="1.5%", roc="0.0%"),
            cn_10y_yield=MacroMetric(value="2.3%", roc="+0.1%"),
            hk_base_rate=MacroMetric(value="5.75%", roc="0.0%"),
            hk_10y_yield=MacroMetric(value="3.1%", roc="+0.1%"),
            us_cpi=MacroMetric(value="3.1%", roc="-0.1%"),
            jp_cpi=MacroMetric(value="2.0%", roc="0.0%"),
            cn_cpi=MacroMetric(value="0.8%", roc="+0.1%"),
            hk_cpi=MacroMetric(value="1.7%", roc="0.0%"),
            gold=MacroMetric(value="2100", roc="+2.0%"),
            crude_oil=MacroMetric(value="82", roc="+1.5%"),
            us_payrolls=MacroMetric(value="250k", roc="+10k"),
            ind_prod=MacroMetric(value="101.2", roc="+0.2%"),
            housing_starts=MacroMetric(value="1.35m", roc="+0.1%"),
            unemp_rate=MacroMetric(value="4.0%", roc="0.0%"),
            jp_business_index=MacroMetric(value="48.5", roc="+0.3"),
            cn_pmi=MacroMetric(value="50.2", roc="+0.4"),
            hk_retail_sales=MacroMetric(value="-2.1%", roc="+0.5%"),
            hk_unemp_rate=MacroMetric(value="3.2%", roc="0.0%"),
            usd_jpy=MacroMetric(value="149.0", roc="+1.0%"),
            usd_cnh=MacroMetric(value="7.20", roc="+0.2%"),
            usd_hkd=MacroMetric(value="7.82", roc="0.0%"),
            nikkei_225=MacroMetric(value="39000", roc="+3.0%"),
            sp_500=MacroMetric(value="5200", roc="+2.0%"),
            csi_300=MacroMetric(value="3600", roc="+1.5%"),
            hang_seng_index=MacroMetric(value="16800", roc="+1.0%"),
            us_vix=MacroMetric(value="14.5", roc="-0.5"),
            nikkei_vi=MacroMetric(value="18.0", roc="-0.4"),
            vhsi=MacroMetric(value="19.2", roc="-0.3"),
        ),
    )
    pm_request = pm_agent.build_request(
        request_id="req-pm-rt-001",
        security_id=security_id,
        as_of_date=date(2026, 3, 13),
        macro_report=AgentResponse(
            request_id="m",
            agent=AgentRole.MACRO,
            security_id=security_id,
            as_of_date=date(2026, 3, 13),
            reasoning="Liquidity remains supportive.",
            score=63.0,
        ),
        sector_report=AgentResponse(
            request_id="s",
            agent=AgentRole.SECTOR,
            security_id=security_id,
            as_of_date=date(2026, 3, 13),
            reasoning="The stock is leading its peers.",
            score=71.0,
        ),
    )

    prompts = {
        "technical": f"System Prompt:\n{technical_agent.render_prompts(technical_request)[0]}\n\nUser Prompt:\n{technical_agent.render_prompts(technical_request)[1]}",
        "quant": f"System Prompt:\n{quant_agent.render_prompts(quant_request)[0]}\n\nUser Prompt:\n{quant_agent.render_prompts(quant_request)[1]}",
        "qualitative": f"System Prompt:\n{qualitative_agent.render_prompts(qualitative_request)[0]}\n\nUser Prompt:\n{qualitative_agent.render_prompts(qualitative_request)[1]}",
        "news": f"System Prompt:\n{news_agent.render_prompts(news_request)[0]}\n\nUser Prompt:\n{news_agent.render_prompts(news_request)[1]}",
        "sector": f"System Prompt:\n{sector_agent.render_prompts(sector_request)[0]}\n\nUser Prompt:\n{sector_agent.render_prompts(sector_request)[1]}",
        "macro": f"System Prompt:\n{macro_agent.render_prompts(macro_request)[0]}\n\nUser Prompt:\n{macro_agent.render_prompts(macro_request)[1]}",
        "pm": f"System Prompt:\n{pm_agent.render_prompts(pm_request)[0]}\n\nUser Prompt:\n{pm_agent.render_prompts(pm_request)[1]}",
    }

    assert prompts == {
        "technical": "\n".join(
            [
                "System Prompt:",
                "Role: You are a technical analyst on the trading team. Your task is to forecast stock prices one month ahead based strictly on technical indicators to assist portfolio managers.",
                "",
                "Policy & Constraints:",
                "- Input scope: Use only the provided technical indicators; disregard news or fundamentals.",
                "- Scoring: Provide a score between 0 and 100 based on a balanced assessment of momentum, oscillators, and volatility.",
                "- Scale interpretation:",
                "  - 100: Strong long recommendation",
                "  - 50: Neutral (no clear advantage)",
                "  - 0: Strong short recommendation",
                "- Output requirements: strictly JSON format, including a brief one-sentence comment in English.",
                "",
                "User Prompt:",
                "Instruction: The following are technical indicators for a particular stock in CN at the end of a given month. Based on these, please rate the attractiveness of long or short positions in this stock on a scale of 0 to 100 points.",
                "",
                "Technical indicators used:",
                "- Momentum: RoC (Rate of Change)",
                "  Percentage change in price over the past n days (n = 5, 10, 20, compared to previous month) and m months (n = 1, 3, 6, 12).",
                "- Volatility: Bollinger Band Deviation",
                "  Actual value used: (Close - 20-day MA) / 20-day Close standard deviation",
                "- Oscillators:",
                "  MACD: (12-day EMA - 26-day EMA) / Close price. Normalized by dividing by Close.",
                "  RSI: Ranges from 0 to 100. (100 x Upward Avg) / (Upward Avg + Downward Avg).",
                "  Stochastic Oscillator: Uses K, D, J indicators.",
                "",
                "Evaluation Rules:",
                "- Comprehensively assess the risk-reward ratio for the next month based on the combination of indicators.",
                "- Check consistency among momentum, oscillators, and volatility.",
                "- 100: Strong Long, 0: Strong Short, 50: Neutral.",
                "- State the reason in English in one sentence.",
                "",
                "Output Format:",
                "{",
                '  "score": <integer 0-100>,',
                '  "reason": "<explanation in English>"',
                "}",
                "",
                "This Month's Technical Indicators:",
                "RoC 5day: None%",
                "RoC 10day: None%",
                "RoC 20day: None%",
                "RoC 1Month: None%",
                "RoC 3Month: None%",
                "RoC 6Month: None%",
                "RoC 12Month: None%",
                "RSI: None",
                "MACD: None",
                "Signal: None",
                "Hist: None",
                "Stochastic",
                "%K: None",
                "%D: None",
                "%J: None",
            ]
        ),
        "quant": "\n".join(
            [
                "System Prompt:",
                "Role: You are a quantitative fundamental analyst on the research team.",
                "",
                "Policy & Constraints:",
                "- Use only the provided quantitative fundamental metrics.",
                "- Ignore news, sentiment, macro, and technical price patterns.",
                "- Evaluate medium-to-long-term attractiveness for a long/short decision.",
                "- Compare the latest visible reporting period against the previous visible reporting period.",
                '- Missing values marked "n/a" must not be invented; judge from the remaining evidence.',
                "- Output must be strictly one JSON object.",
                '- "reason" must be one short English sentence.',
                "",
                "User Prompt:",
                "Instruction: Evaluate the attractiveness of this stock for a long/short position (0-100) using only the latest visible reporting period and the previous visible reporting period.",
                "",
                "Rules & Definitions:",
                "- Focus on Profitability, Value, Cash Flow quality, Financial Health, and Growth.",
                "- Each metric is shown as: latest visible value (diff vs previous visible reporting period).",
                '- "Current Date" is the evaluation date for this prompt.',
                "- TTM means trailing twelve months and is used for flow variables and flow-derived ratios to mitigate seasonality while incorporating the most recent performance.",
                "- In this appendix, treat Net Margin, ROA, ROE, Asset Turn, Inv. Turn Days, PER, FCF, Margin, EBITDA, Sales YoY, CAGR 3Y, EPS Growth, and DPS as TTM-style metrics when available.",
                "- Do not treat stock variables as TTM; Equity Ratio, Quick Ratio, and D/E Ratio are point-in-time balance-sheet snapshots from the latest visible filing.",
                '- Treat "n/a" as unavailable evidence, not as good or bad by itself.',
                "- Higher score means more attractive for a long position; lower score means more attractive for a short position.",
                "",
                "Output Format (JSON only):",
                "{",
                '  "score": <integer 0-100>,',
                '  "reason": "<explanation in English>"',
                "}",
                "",
                "Stock Data [Format: Value (diff: Value)]:",
                "Current Date: 2026-03-13",
                "[Profitability] ",
                "Net Margin: 21% (diff: +1%)",
                "ROA: 12% (diff: +1%)",
                "ROE: 18% (diff: +2%)",
                "Asset Turn: 0.8 (diff: +0.1)",
                "Inv. Turn Days: 35 (diff: -2)",
                "[Value] ",
                "PER: 28 (diff: +1)",
                "[Cash Flow]",
                "FCF: 45 (diff: +3%)",
                "Margin: 15% (diff: +1%)",
                "EBITDA: 60 (diff: +4%)",
                "[Health]",
                "Equity Ratio: 55% (diff: +1%)",
                "Quick Ratio: 1.4 (diff: +0.1)",
                "D/E Ratio: 0.3 (diff: -0.1)",
                "[Growth]",
                "Sales YoY: 10% (diff: +2%)",
                "CAGR 3Y: 8% (diff: +1%)",
                "EPS Growth: 12% (diff: +3%)",
                "DPS: 4.2 (diff: +0.2)",
            ]
        ),
        "qualitative": "\n".join(
            [
                "System Prompt:",
                'Role: You are a Strategic Analyst reporting to the Portfolio Manager. Your mission is to analyze qualitative corporate disclosures and provide a "Fundamental Risk & Catalyst Report" for the upcoming 1-month horizon.',
                "",
                "Perspective & Analysis Logic:",
                '- Filter: Distinguish between "stagnant boilerplate text" and "meaningful strategic shifts."',
                "- Focus: Identify qualitative triggers (catalysts or red flags) rather than just long-term value.",
                "- Target: Operational momentum, management credibility, and hidden structural risks.",
                "",
                "Guidelines:",
                "- Inputs: Excerpts from Securities Reports (Business Overview, Risks, MD&A, Governance).",
                '- Outputs: Three specific scores (1-5) and a strategic summary ("Insight").',
                '- Format: Return ONLY a JSON object. The "insight" must be written in English.',
                "",
                "User Prompt:",
                "Instruction: Evaluate qualitative corporate data to advise the PM on stock attractiveness and potential risks for the next 1 month.",
                "",
                "Evaluation Items (Score 1-5):",
                "1. Business Momentum: Strength of cycle/strategy.",
                "   (1: Deteriorating/Vague -> 5: Strong tailwinds/Clear execution)",
                "2. Immediate Risk Severity: Probability of risks manifesting.",
                "   (1: High risk/Urgent -> 5: Low risk/Stable)",
                "3. Management Trust: Credibility & oversight structure.",
                "   (1: Untrustworthy -> 5: Transparent/Aligned)",
                "",
                "Rules & Output:",
                '- Focus: Look for "Changes" in tone or new risk factors.',
                "- Insight: Professional briefing in English.",
                "- Format: JSON with scores and insight.",
                "",
                "Input Data (Text Excerpts):",
                "Info Update: Yes",
                "[1. Overview] New channels are expanding.",
                "[2. Risks] Input costs remain elevated.",
                "[3. MD&A] Margin recovery is underway.",
                "[4. Governance] Board refresh is progressing.",
                "",
                "Output Format (JSON only):",
                "{",
                '  "business_momentum": <integer 1-5>,',
                '  "immediate_risk": <integer 1-5>,',
                '  "management_trust": <integer 1-5>,',
                '  "insight": "<strategic summary in English>"',
                "}",
            ]
        ),
        "news": "\n".join(
            [
                "System Prompt:",
                "Role: You are a Senior News Analyst specializing in the stock market. Your task is to analyze news headlines and summaries from the past month to provide qualitative insights that complement fundamental scores.",
                "",
                "Evaluation Guidelines:",
                '- Perspectives: Evaluate impact on "Return Outlook" (Upside) and "Risk Outlook" (Downside).',
                "- Scoring Scale (1-5):",
                "  - 1: Minimal/None -> 3: Moderate -> 5: Extreme",
                "- Analysis Logic: Distinguish between temporary noise and structural changes (e.g., product launches, regulations, ESG).",
                "- Output: JSON format only. Reason must be a concise English summary.",
                "",
                "User Prompt:",
                'Instruction: Evaluate "Return Outlook" and "Risk Outlook" (1-3 months) based on the provided news articles.',
                "",
                "Evaluation Criteria (Score 1-5):",
                "- Return Outlook: Positive momentum (e.g., new products, expansion).",
                "- Risk Outlook: Potential downside/uncertainty (e.g., supply chain, lawsuits).",
                "",
                "Rules & Output:",
                "- Balance: Identify risks even if news is generally positive.",
                '- Empty Case: If no news, set both scores to 1 and reason "No News".',
                "- Format: JSON with scores (1-5) and English reason (about 100 chars).",
                "",
                "News List for the Month:",
                "  - [2026-03-12T09:00:00] Premium line launched / The company launched a premium line.",
                "",
                "Output Format (JSON only):",
                "{",
                '  "return_outlook": <integer 1-5>,',
                '  "risk_outlook": <integer 1-5>,',
                '  "reason": "<concise English summary>"',
                "}",
            ]
        ),
        "sector": "\n".join(
            [
                "System Prompt:",
                "Role: You are a Sector Specialist on the investment committee. Your task is to synthesize reports from Technical, Quantitative, and Qualitative sub-analysts to provide a definitive 1-month investment recommendation.",
                "",
                "Synthesis Logic & Perspective:",
                '- The "Bridge": Connect raw multi-angle analysis to PM execution.',
                '- Metaphor: Tech/Quant act as the "Engine" (price/value); Qualitative acts as the "Steering" (hazards).',
                "- Dynamic Weighting: Adjust weights based on consistency and sector environment (e.g., high volatility -> prioritize risk).",
                "",
                "Guidelines:",
                "- Sector Context: Compare metrics against sector averages to identify Leaders vs. Laggards.",
                "- Output: Final Conviction Score (0-100) and a comprehensive Investment Thesis.",
                "",
                "User Prompt:",
                "Instruction: As the Sector Specialist, review the analyst reports and sector data to provide a final recommendation (Conviction Score & Investment Thesis).",
                "",
                "1. Sub-Analyst Reports:",
                "- Technical Analyst: <Score=72.0, Comment=Momentum is constructive.>",
                "- Quant Fundamental Analyst: <Score=68.0, Comment=Cash flow remains resilient.>",
                "- Qualitative Strategic Analyst: <Score=n/a, Comment=Execution is improving.>",
                "",
                "2. Sector & Comparative Context.",
                "Compare Target vs. Sector Avg using Rate of Change (RoC) for specific items:",
                "- P/L Items: ",
                "  - Sales",
                "    target: +12% vs. sector: +8%",
                "  - Op Profit",
                "    target: n/a% vs. sector: n/a%",
                "  - Net Income",
                "    target: n/a% vs. sector: n/a%",
                "  - Cost of Sales",
                "    target: n/a% vs. sector: n/a%",
                "  - Depreciation",
                "    target: n/a% vs. sector: n/a%",
                "- B/S Items: ",
                "  - Total Assets",
                "    target: n/a% vs. sector: n/a%",
                "  - Equity",
                "    target: n/a% vs. sector: n/a%",
                "  - Cash",
                "    target: n/a% vs. sector: n/a%",
                "  - Receivables",
                "    target: n/a% vs. sector: n/a%",
                "  - Inventory",
                "    target: n/a% vs. sector: n/a%",
                "  - Financial Assets",
                "    target: n/a% vs. sector: n/a%",
                "  - Interest Bearing Debt",
                "    target: n/a% vs. sector: n/a%",
                "  - Cur. Liabilities",
                "    target: n/a% vs. sector: n/a%",
                "  - Issued Shares",
                "    target: n/a% vs. sector: n/a%",
                "- CF & Others: ",
                "  - Op CF",
                "    target: n/a% vs. sector: n/a%",
                "  - Investing CF",
                "    target: n/a% vs. sector: n/a%",
                "  - Dividends",
                "    target: n/a% vs. sector: n/a%",
                "  - Monthly Close",
                "    target: n/a% vs. sector: n/a%",
                "",
                "3. Tasks for PM Report:",
                "1. Conviction Score (0-100): Integrate views & sector strength. (100: Outperform, 0: Underperform).",
                "2. Comprehensive Thesis: Synthesize alignment/conflict between Tech/Fund/Sector. Highlight catalysts/risks. (in English).",
                "",
                "Output Format (JSON only):",
                "{",
                '  "score": <integer 0-100>,',
                '  "investment_thesis": "<comprehensive thesis in English>"',
                "}",
            ]
        ),
        "macro": "\n".join(
            [
                "System Prompt:",
                "Role: You are a Macro Analyst on the trading team. Your task is to analyze macro indicators relevant to US to identify factors influencing the 1-month return of US.",
                "",
                "Evaluation Areas (Label & Score 0-100):",
                "- Market Trend: Bullish/Bearish (Overall outlook).",
                "- Risk: Risk sentiment and potential volatility.",
                "- Economy: Economic growth trends.",
                "- Rates: Interest rate environment.",
                "- Inflation: Price level trends.",
                "",
                "Policy & Constraints:",
                "- Input Scope: Use only provided indicators; do not interpret news.",
                '- Scoring Logic: Based on "Levels" and "Rate of Change" of indicators.',
                "- Output Requirement: Strictly JSON format.",
                "- Summary: Concise comment in English.",
                "",
                "User Prompt:",
                'Instruction: Evaluate the current macroeconomic environment to impact the 1-month forward return of US, based on "Levels" and "RoC" (Rate of Change).',
                "",
                "Evaluation Items & Scoring Rules (0-100): Score 100: Strong Buy (Bullish), 50: Neutral, 0: Strong Sell (Bearish).",
                "- Market Trend: Stock indices momentum. (High: Upward trend).",
                "- Risk Environment: VIX & Safe assets. (High Score: Low VIX/Stable Risk-on).",
                "- Economic Growth: Employment, Production. (High: Expansion).",
                "- Interest Rates: Levels & Direction. (High Score: Accommodative/Falling).",
                "- Inflation: Prices & Commodities. (High Score: Stable/Disinflation. Low Score: Stagflation/Deflation).",
                "",
                "Output Format (JSON only):",
                "{",
                '  "metrics": { ',
                '    "market_trend": <score, integer 0-100>,',
                '    "risk_environment": <score, integer 0-100>,',
                '    "economic_growth": <score, integer 0-100>,',
                '    "interest_rates": <score, integer 0-100>,',
                '    "inflation": <score, integer 0-100>',
                "  },",
                '  "summary": "<Implications for active management in English>"',
                "}",
                "",
                "Macro Indicators [Format: Value (RoC: Value%)]:",
                "[1. Rates & Policy]",
                "US Fed Rate: 5.25% (RoC: 0.0%)",
                "US 10Y Yield: 4.2% (RoC: +0.1%)",
                "JP Policy Rate: 0.5% (RoC: 0.0%)",
                "JP 10Y Yield: 1.1% (RoC: +0.1%)",
                "CN Policy Rate: 1.5% (RoC: 0.0%)",
                "CN 10Y Yield: 2.3% (RoC: +0.1%)",
                "HK Base Rate: 5.75% (RoC: 0.0%)",
                "HK 10Y Yield: 3.1% (RoC: +0.1%)",
                "[2. Inflation & Commodities]",
                "US CPI: 3.1% (RoC: -0.1%)",
                "JP CPI: 2.0% (RoC: 0.0%)",
                "CN CPI: 0.8% (RoC: +0.1%)",
                "HK CPI: 1.7% (RoC: 0.0%)",
                "Gold: 2100 (RoC: +2.0%)",
                "Crude Oil: 82 (RoC: +1.5%)",
                "[3. Growth & Economy]",
                "US Payrolls: 250k (RoC: +10k)",
                "Ind. Prod: 101.2 (RoC: +0.2%)",
                "Housing Starts: 1.35m (RoC: +0.1%)",
                "Unemp. Rate: 4.0% (RoC: 0.0%)",
                "JP Business Index: 48.5 (RoC: +0.3)",
                "CN PMI: 50.2 (RoC: +0.4)",
                "HK Retail Sales: -2.1% (RoC: +0.5%)",
                "HK Unemp. Rate: 3.2% (RoC: 0.0%)",
                "[4. Market & Risk]",
                "USD/JPY: 149.0 (RoC: +1.0%)",
                "USD/CNH: 7.20 (RoC: +0.2%)",
                "USD/HKD: 7.82 (RoC: 0.0%)",
                "Nikkei 225: 39000 (RoC: +3.0%)",
                "S&P 500: 5200 (RoC: +2.0%)",
                "CSI 300: 3600 (RoC: +1.5%)",
                "Hang Seng Index: 16800 (RoC: +1.0%)",
                "US VIX: 14.5 (RoC: -0.5)",
                "Nikkei VI: 18.0 (RoC: -0.4)",
                "VHSI: 19.2 (RoC: -0.3)",
            ]
        ),
        "pm": "\n".join(
            [
                "System Prompt:",
                "Role: You are the Chief Portfolio Manager (PM). Your task is to determine the definitive investment score by integrating Top-Down Macro analysis with Bottom-Up Sector/Stock analysis.",
                "",
                "Decision Logic (Integration Strategy):",
                "- Goal: Maximize alpha (1-month horizon) while strictly managing risk.",
                '- Harmonization: Balance "Market Context" (Macro) vs. "Stock Specifics".',
                '- Macro Alignment: If Macro is "Risk-Off", apply a conservative discount (lower scores) unless the stock has exceptional defensive qualities.',
                "- Tie-Breaking: Use Macro context to resolve conflicts between Technicals and Fundamentals (e.g., High Inflation -> favor fundamental pricing power over momentum).",
                "",
                "Output Requirements:",
                "- Final Score: 0-100 (Definitive conviction).",
                "- Rationale: Decisive professional rationale justifying the integration in English.",
                "",
                "User Prompt:",
                "Instruction: As the Portfolio Manager, review the Macro and Sector-level inputs to provide your final investment decision for the next 1 month.",
                "",
                "Input Reports (Integration):",
                "[1. Macro Environment Report]",
                "  {",
                '    "score": 63.0,',
                '    "reason": "Liquidity remains supportive."',
                "  }",
                "[2. Sector Specialist Report]",
                "  {",
                '    "score": 71.0,',
                '    "reason": "The stock is leading its peers."',
                "  }",
                "",
                "Final Decision Tasks:",
                "1. Final Investment Score (0-100):",
                "   - 100: Maximum Overweight (High conviction, perfect alignment).",
                "   - 50: Neutral/Hold (Market-weight, no clear edge).",
                "   - 0: Strong Underweight/Avoid (High risk).",
                "2. Final Rationale (English):",
                "   - Explain macro influence on this specific stock.",
                "   - Summarize key reasons & risk-reward balance (30 days).",
                "",
                "Output Format (JSON only):",
                "{",
                '  "final_score": <integer 0-100>,',
                '  "reason": "<decisive rationale in English>"',
                "}",
            ]
        ),
    }
